site_name: Render Wagon - Specification
site_description: This website contains the specification documentation related to Render Wagon
site_author: Render Wagon Team
site_url: https://specification.renderwagon.dev

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.tabs.sticky

extra:
  version:
    provider: mike
    custom_dir: overrides

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

  - mike:
      canonical_version: 'latest'
