name: Publish to Pages
on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
            
      # Runs a single command using the runners shell
      - name: Determine version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          format: "${major}.${minor}.${increment}"
          bump_each_commit: true
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to ${{ steps.version.outputs.version }},
          echo test, and deploy your project from a build.
