name: Publish to Pages
on:
  push:
    branches: [ "main" ]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Root
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to get all commits and determine version.

      - name: Fetch Pages Commits
        run: git fetch origin gh-pages --depth=1

      - name: Determine version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          format: "${major}.${minor}.${patch}"
          bump_each_commit: true

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
        name: Setup environment

      - run: pip install \
          mkdocs-material \
          mkdocs-minify-plugin \
          mkdocs-redirects \
          mike
        name: Install dependencies

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - run: mike set-default latest
        name: Set default version

      - run: mike deploy --push --update-aliases ${{ steps.version.outputs.version }} latest
        name: Deploy to GitHub Pages

